@echo off
REM This batch file helps execute the SQL scripts to update questions and their media
REM Created on July 10, 2025

echo ======================================================================
echo               Update Exercises with Topic-Related Questions
echo ======================================================================
echo.
echo This utility will help you update questions to ensure:
echo 1. Each exercise has multiple questions related to its topic
echo 2. All questions have appropriate audio and image support
echo 3. Question content is consistent with the exercise data
echo.
echo The following scripts will be executed:
echo.
echo 1. update_exercises_with_topic_questions.sql
echo    - Adds topic-specific questions to exercises that have only one question
echo.
echo 2. update_questions_media_paths.sql 
echo    - Updates media paths to ensure all questions have proper audio/image support
echo    - This SQL will be generated by running the verify_question_media.py script
echo.

set /p continue="Do you want to continue? (Y/N): "
if /i "%continue%" NEQ "Y" goto end

echo.
echo Step 1: Generating media update SQL script...
cd %~dp0

REM Check if Python is installed
python --version >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    echo Python is installed. Running media verification script...
    python verify_question_media.py
) else (
    echo Python is not installed or not in PATH. Skipping media verification.
    echo You can run the script manually later with: python verify_question_media.py
)

echo.
echo Step 2: SQL Scripts are ready for execution.
echo.
echo To execute the SQL scripts in your MySQL database:
echo.
echo Option 1: Using MySQL Command Line
echo   mysql -u YOUR_USERNAME -p YOUR_DATABASE < database/migrations/update_exercises_with_topic_questions.sql
echo   mysql -u YOUR_USERNAME -p YOUR_DATABASE < database/migrations/update_questions_media_paths.sql
echo.
echo Option 2: Using phpMyAdmin
echo   1. Open phpMyAdmin and select your database
echo   2. Go to the "Import" tab
echo   3. Select the SQL files and import them
echo.

set /p mysql="Do you want to run the SQL scripts using MySQL command line? (Y/N): "
if /i "%mysql%" NEQ "Y" goto end

set /p username="Enter MySQL username: "
set /p password="Enter MySQL password: "
set /p database="Enter database name: "

echo.
echo Running SQL scripts...
echo.

mysql -u %username% -p%password% %database% < database/migrations/update_exercises_with_topic_questions.sql
if %ERRORLEVEL% EQU 0 (
    echo Successfully executed update_exercises_with_topic_questions.sql
) else (
    echo Failed to execute update_exercises_with_topic_questions.sql
)

if exist database\migrations\update_questions_media_paths.sql (
    mysql -u %username% -p%password% %database% < database/migrations/update_questions_media_paths.sql
    if %ERRORLEVEL% EQU 0 (
        echo Successfully executed update_questions_media_paths.sql
    ) else (
        echo Failed to execute update_questions_media_paths.sql
    )
) else (
    echo Media paths SQL file not found. Make sure to run verify_question_media.py first.
)

echo.
echo Process complete!
echo.

:end
pause
