import os
import json
import re

def generate_sync_sql():
    """Generate SQL script to sync questions with exercises data."""
    
    # Path to exercises SQL dump file (adjust if needed)
    exercises_sql_path = '../exercises_dump.sql'
    
    # If the file doesn't exist, look for it in the current directory
    if not os.path.exists(exercises_sql_path):
        exercises_sql_path = 'exercises_dump.sql'
    
    # Output file path
    output_sql_path = 'database/migrations/sync_questions_with_exercises.sql'
    
    # Check if exercises SQL file exists
    if not os.path.exists(exercises_sql_path):
        print(f"Error: Exercises SQL file not found at {exercises_sql_path}")
        return
    
    # Read exercises SQL file
    with open(exercises_sql_path, 'r', encoding='utf-8') as f:
        exercises_sql = f.read()
    
    # Extract exercise data using regex
    # This pattern needs to match your actual INSERT statement format
    pattern = r"INSERT INTO `exercises` \(.*?\) VALUES\s*\((.*?)\);"
    exercises_data = re.findall(pattern, exercises_sql, re.DOTALL)
    
    # Create SQL header
    sql_output = """-- SQL Script to synchronize questions with exercises data
-- Generated by Python script on July 10, 2025
-- This script updates question_text, audio_url, image_url, and options (A, B, C, D) in the questions table
-- based on corresponding data in the exercises table

-- First, create a backup of the questions table (recommended)
CREATE TABLE IF NOT EXISTS questions_backup LIKE questions;
INSERT INTO questions_backup SELECT * FROM questions;

"""
    
    # Process each exercise
    for i, exercise_data in enumerate(exercises_data, 1):
        # Parse exercise values (this depends on your actual data format)
        # In a real scenario, you'd need more robust parsing logic
        values = exercise_data.split(',')
        
        # Extract data (adjust indices based on your column order)
        exercise_id = values[0].strip()
        title = values[-4].strip().strip("'")
        question = values[-8].strip().strip("'")
        audio_url = values[1].strip().strip("'")
        image_url = values[8].strip().strip("'")
        
        # Extract options (this is simplified, would need more robust parsing)
        options_str = values[-6].strip()
        try:
            options = json.loads(options_str)
            option_a = options[0].replace('A. ', '')
            option_b = options[1].replace('B. ', '')
            option_c = options[2].replace('C. ', '')
            option_d = options[3].replace('D. ', '')
        except:
            # Fallback if JSON parsing fails
            option_a = "Option A"
            option_b = "Option B"
            option_c = "Option C"
            option_d = "Option D"
        
        # Generate SQL update statement
        sql_output += f"""
-- Update questions for {title}
UPDATE questions
SET 
    question_text = '{question}',
    audio_url = '/files/audio/{audio_url}',
    image_url = '/files/images/{image_url}',
    option_a = '{option_a}',
    option_b = '{option_b}',
    option_c = '{option_c}',
    option_d = '{option_d}'
WHERE exercise_id = {exercise_id};

"""
    
    # Add alternative direct SQL approach
    sql_output += """
-- Alternative direct SQL update for all questions (more efficient)
UPDATE questions q
JOIN exercises e ON q.exercise_id = e.id
SET 
    q.question_text = e.question,
    q.audio_url = CONCAT('/files/audio/', e.audio_url),
    q.image_url = CONCAT('/files/images/', e.image_url),
    q.option_a = SUBSTRING_INDEX(SUBSTRING_INDEX(REPLACE(REPLACE(e.options, '[', ''), ']', ''), '", "', 1), '"', -1),
    q.option_b = SUBSTRING_INDEX(SUBSTRING_INDEX(REPLACE(REPLACE(e.options, '[', ''), ']', ''), '", "', 2), '"', -1),
    q.option_c = SUBSTRING_INDEX(SUBSTRING_INDEX(REPLACE(REPLACE(e.options, '[', ''), ']', ''), '", "', 3), '"', -1),
    q.option_d = SUBSTRING_INDEX(SUBSTRING_INDEX(REPLACE(REPLACE(e.options, '[', ''), ']', ''), '", "', 4), '"', -1);
"""
    
    # Write SQL to output file
    os.makedirs(os.path.dirname(output_sql_path), exist_ok=True)
    with open(output_sql_path, 'w', encoding='utf-8') as f:
        f.write(sql_output)
    
    print(f"SQL script generated at {output_sql_path}")

def create_new_questions_table():
    """Generate SQL to create a new questions table with data from exercises."""
    
    output_sql_path = 'database/migrations/create_new_questions_from_exercises.sql'
    
    sql_output = """-- SQL Script to create a new questions table with data from exercises
-- Generated by Python script on July 10, 2025

-- Create new table
DROP TABLE IF EXISTS questions_new;
CREATE TABLE questions_new (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    exercise_id BIGINT NOT NULL,
    question_text VARCHAR(255) NOT NULL,
    question_type VARCHAR(50) DEFAULT 'multiple_choice',
    option_a VARCHAR(255),
    option_b VARCHAR(255),
    option_c VARCHAR(255),
    option_d VARCHAR(255),
    correct_answer VARCHAR(50) NOT NULL,
    explanation TEXT,
    difficulty_level VARCHAR(20) DEFAULT 'EASY',
    points INT DEFAULT 10,
    question_order INT,
    is_active TINYINT(1) DEFAULT 1,
    audio_url VARCHAR(255),
    image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (exercise_id) REFERENCES exercises(id)
);

-- Insert data from exercises table
INSERT INTO questions_new (
    exercise_id, 
    question_text, 
    question_type,
    option_a, 
    option_b, 
    option_c, 
    option_d, 
    correct_answer, 
    explanation, 
    difficulty_level, 
    points, 
    question_order, 
    is_active, 
    audio_url, 
    image_url
)
SELECT 
    e.id as exercise_id,
    e.question as question_text,
    CASE 
        WHEN e.type = 'multiple_choice' THEN 'multiple_choice'
        WHEN e.type = 'fill_in_the_blank' THEN 'fill_in_blank'
        WHEN e.type = 'matching' THEN 'matching'
        ELSE 'multiple_choice'
    END as question_type,
    SUBSTRING_INDEX(SUBSTRING_INDEX(REPLACE(REPLACE(e.options, '[', ''), ']', ''), '", "', 1), '"', -1) as option_a,
    SUBSTRING_INDEX(SUBSTRING_INDEX(REPLACE(REPLACE(e.options, '[', ''), ']', ''), '", "', 2), '"', -1) as option_b,
    SUBSTRING_INDEX(SUBSTRING_INDEX(REPLACE(REPLACE(e.options, '[', ''), ']', ''), '", "', 3), '"', -1) as option_c,
    SUBSTRING_INDEX(SUBSTRING_INDEX(REPLACE(REPLACE(e.options, '[', ''), ']', ''), '", "', 4), '"', -1) as option_d,
    e.correct_answer,
    e.explanation,
    CASE 
        WHEN e.difficulty_level = 'easy' THEN 'EASY'
        WHEN e.difficulty_level = 'medium' THEN 'MEDIUM'
        WHEN e.difficulty_level = 'hard' THEN 'HARD'
        ELSE 'EASY'
    END as difficulty_level,
    e.points,
    e.order_index as question_order,
    e.is_active,
    CONCAT('/files/audio/', e.audio_url) as audio_url,
    CONCAT('/files/images/', e.image_url) as image_url
FROM exercises e;

-- Verification queries
SELECT COUNT(*) FROM questions_new;
SELECT * FROM questions_new LIMIT 10;

-- To replace the original questions table, uncomment the following:
-- RENAME TABLE questions TO questions_old, questions_new TO questions;
"""
    
    # Write SQL to output file
    os.makedirs(os.path.dirname(output_sql_path), exist_ok=True)
    with open(output_sql_path, 'w', encoding='utf-8') as f:
        f.write(sql_output)
    
    print(f"SQL script generated at {output_sql_path}")

if __name__ == "__main__":
    # Generate sync SQL
    generate_sync_sql()
    
    # Create new questions table SQL
    create_new_questions_table()
    
    print("SQL generation complete!")
